# Generated by Django 4.1.1 on 2022-11-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employeedetails_empdept_employeeexperience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='comapny1duration',
            new_name='company1duration',
        ),
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='comapny2duration',
            new_name='company2duration',
        ),
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='comapny3duration',
            new_name='company3duration',
        ),
    ]
