# Generated by Django 4.2.4 on 2023-09-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_rename_comapny1duration_employeeexperience_company1duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hellouser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company1name', models.CharField(max_length=100, null=True)),
                ('company1desig', models.CharField(max_length=100, null=True)),
                ('company1salary', models.CharField(max_length=100, null=True)),
                ('company1duration', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
